apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"

build:
  local:
    push: false
  artifacts:
    - image: rohithputha/findpartnerauth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js
    - image: rohithputha/findpartnerprofile
      context: profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js
    - image: rohithputha/findpartnerrecommendation
      context: recommendation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js